using System;

[Serializable]
public enum EnumWindowTypes
{
	NONE_1 = 1,
	TALK_D_NONAME,
	TALK_D,
	TALK_U,
	TALK_U_NONAME,
	TALK_D_ANGEL,
	TALK_U_ANGEL,
	TALK_D_ANGEL_FACE,
	TALK_U_ANGEL_FACE,
	TALK_U_NONAME_ANGLE,
	TALK_D_DEVIL,
	TALK_U_DEVIL,
	TALK_D_DEVIL_FACE,
	TALK_U_DEVIL_FACE,
	TALK_U_NONAME_DEVIL,
	TALK_D_NO_BUTTON,
	TALK_D_ANGEL_NO_BUTTON,
	TALK_D_DEVIL_NO_BUTTON
}
